refactor: modernize package
MapColonies/error-express-handler pull request #12
Opened 2024-09-18 12:26 UTC by CptSchnitz

2024-09-19 10:11 UTC, netanelC requested changes

2024-09-19 10:11 UTC, netanelC commented on .github/dependabot.yml
> +      - dependency-name: '@map-colonies/schemas'
Remove it

2024-09-19 10:11 UTC, netanelC commented on .github/workflows/release-pleate.yaml
> +on:
Change name of file

2024-09-23 11:17 UTC, CptSchnitz commented on .github/dependabot.yml
> +      - dependency-name: '@map-colonies/schemas'
fixed

2024-09-23 11:17 UTC, CptSchnitz commented on .github/workflows/release-pleate.yaml
> +on:
fixed

2024-09-24 06:06 UTC, netanelC approved these changes

2024-09-24 10:35 UTC, merged